# Generated by Django 5.2.9 on 2025-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('in_app', 'In-App'), ('teams', 'Teams')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('destination', models.CharField(help_text='Email address, Webhook URL, etc.', max_length=255)),
            ],
            options={
                'unique_together': {('user_id', 'channel')},
            },
        ),
    ]
